// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Ship.proto

package protout

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Ship struct {
	Shipname    string             `protobuf:"bytes,1,opt,name=shipname,proto3" json:"shipname,omitempty"`
	CaptainName string             `protobuf:"bytes,2,opt,name=CaptainName,proto3" json:"CaptainName,omitempty"`
	Crew        []*Ship_CrewMember `protobuf:"bytes,3,rep,name=Crew,proto3" json:"Crew,omitempty"`
}

func (m *Ship) Reset()         { *m = Ship{} }
func (m *Ship) String() string { return proto.CompactTextString(m) }
func (*Ship) ProtoMessage()    {}

func (m *Ship) GetShipname() string {
	if m != nil {
		return m.Shipname
	}
	return ""
}

func (m *Ship) GetCaptainName() string {
	if m != nil {
		return m.CaptainName
	}
	return ""
}

func (m *Ship) GetCrew() []*Ship_CrewMember {
	if m != nil {
		return m.Crew
	}
	return nil
}

type Ship_CrewMember struct {
	Id           int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name         string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	SecClearance int32  `protobuf:"varint,3,opt,name=secClearance,proto3" json:"secClearance,omitempty"`
	Position     string `protobuf:"bytes,4,opt,name=position,proto3" json:"position,omitempty"`
}

func (m *Ship_CrewMember) Reset()         { *m = Ship_CrewMember{} }
func (m *Ship_CrewMember) String() string { return proto.CompactTextString(m) }
func (*Ship_CrewMember) ProtoMessage()    {}
func (*Ship_CrewMember) Descriptor() ([]byte, []int) {
	return fileDescriptor_08459ec0c06c7ece, []int{0, 0}
}

var xxx_messageInfo_Ship_CrewMember proto.InternalMessageInfo

func (m *Ship_CrewMember) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Ship_CrewMember) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Ship_CrewMember) GetSecClearance() int32 {
	if m != nil {
		return m.SecClearance
	}
	return 0
}

func (m *Ship_CrewMember) GetPosition() string {
	if m != nil {
		return m.Position
	}
	return ""
}

func init() {
	proto.RegisterType((*Ship)(nil), "protout.Ship")
	proto.RegisterType((*Ship_CrewMember)(nil), "protout.Ship.CrewMember")
}

func init() { proto.RegisterFile("Ship.proto", fileDescriptor_08459ec0c06c7ece) }

var fileDescriptor_08459ec0c06c7ece = []byte{
	// 190 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x8f, 0xbd, 0x0e, 0x82, 0x30,
	0x14, 0x85, 0x03, 0xd4, 0xbf, 0x8b, 0x71, 0xb8, 0x53, 0xc3, 0x44, 0x98, 0x18, 0x0c, 0x83, 0x3e,
	0x02, 0xb3, 0x0e, 0xf8, 0x04, 0x05, 0x9a, 0xd0, 0x44, 0xda, 0xa6, 0xd4, 0xf8, 0xc2, 0x3e, 0x88,
	0xe9, 0xf5, 0x07, 0x9d, 0xda, 0xf3, 0x9d, 0x93, 0x9e, 0x1e, 0x80, 0xcb, 0xa0, 0x6c, 0x65, 0x9d,
	0xf1, 0x06, 0x57, 0x74, 0xdc, 0x7c, 0xf1, 0x88, 0x80, 0x05, 0x8e, 0x19, 0xac, 0xa7, 0x41, 0x59,
	0x2d, 0x46, 0xc9, 0xa3, 0x3c, 0x2a, 0x37, 0xcd, 0x57, 0x63, 0x0e, 0x69, 0x2d, 0xac, 0x17, 0x4a,
	0x9f, 0x83, 0x1d, 0x93, 0xfd, 0x8b, 0x70, 0x0f, 0xac, 0x76, 0xf2, 0xce, 0x93, 0x3c, 0x29, 0xd3,
	0x03, 0xaf, 0xde, 0xcf, 0x57, 0x54, 0x19, 0x9c, 0x93, 0x1c, 0x5b, 0xe9, 0x1a, 0x4a, 0x65, 0x16,
	0x60, 0x66, 0xb8, 0x83, 0x58, 0xf5, 0xd4, 0xb9, 0x68, 0x62, 0xd5, 0x23, 0x02, 0xd3, 0x73, 0x0d,
	0xdd, 0xb1, 0x80, 0xed, 0x24, 0xbb, 0xfa, 0x2a, 0x85, 0x13, 0xba, 0x93, 0x3c, 0xa1, 0xf4, 0x1f,
	0x0b, 0x0b, 0xac, 0x99, 0x94, 0x57, 0x46, 0x73, 0xf6, 0x5a, 0xf0, 0xd1, 0xed, 0x92, 0x3e, 0x74,
	0x7c, 0x06, 0x00, 0x00, 0xff, 0xff, 0x9f, 0xb1, 0xc2, 0x52, 0x04, 0x01, 0x00, 0x00,
}
